---
- name: Déploiement de la base de données Foreman
  hosts: tfm_db
  gather_facts: true
  become: true
  roles:
    - role: foreman-db
  tags:
    # - tfm
    - db

- hosts: tfm_db
  gather_facts: true
  become: true
  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
  tags:
    - never
    - monitoring
