---

- hosts: tfm_puppet
  gather_facts: true
  become: true
  roles:
    - role: foreman-puppet
  tags:
    - tfm
    - puppet

- hosts: tfm_puppet
  gather_facts: true
  become: true
  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
  tags:
    - never
    - monitoring
