---
- name: Déploiement de l'application Foreman
  hosts: tfm_app
  gather_facts: true
  become: true
  roles:
    - role: foreman-app
  tags:
    # - tfm
    - app

# fetch oauth_consumer_* info
- hosts: "{{ groups['tfm_app'][0] }}"
  gather_facts: true
  become: true
  tasks:
    - name: Récupérer le fichier de configuration settings.yaml
      slurp:
        src: /etc/foreman/settings.yaml
      register: settingsyaml

    - name: Extraire la clé OAuth consumer
      set_fact:
        oauth_consumer_key: "{{ settingsyaml['content'] | b64decode | regex_findall(':oauth_consumer_key: (.+)') | first }}"

    - name: Extraire le secret OAuth consumer
      set_fact:
        oauth_consumer_secret: "{{ settingsyaml['content'] | b64decode | regex_findall(':oauth_consumer_secret: (.+)') | first }}"
  tags:
    # - tfm
    - app
    - oauth

- hosts: tfm_app
  gather_facts: true
  become: true
  roles:
    - icinga.icinga.repos
    - icinga.icinga.icinga2
  tags:
    - never
    - monitoring
