---

foreman_roles:

###################################################################################################
#  _  _  ___  ___ _____ ___
# | || |/ _ \/ __|_   _/ __|
# | __ | (_) \__ \ | | \__ \
# |_||_|\___/|___/ |_| |___/
#
###################################################################################################

  - name: Hosts users
    description: Role granting permissions to view hosts.
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
        - view_architectures
        search: ""
      - permissions:
        - view_domains
        search: ""
      - permissions:
        - view_hosts
        search: ""
      - permissions:
        - view_media
        search: name ~ "Debian" or name ~ "Windows" or name ~ "ESXi"
      - permissions:
        - view_operatingsystems
        search: name ~ "Debian" or name ~ "Windows" or name ~ "ESXi"
      - permissions:
        - view_ptables
        search: name = "Preseed default LVM" or name = "Windows default partition table" or name = "Kickstart default"
      - permissions:
        - view_provisioning_templates
        search: ""
      - permissions:
        - view_subnets
        search: ""

  - name: Hosts admins
    description: Role granting permissions to manage hosts.
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
        - view_architectures
        search: ""
      - permissions:
        - view_domains
        search: ""
      - permissions:
        - view_hosts
        - create_hosts
        - edit_hosts
        - destroy_hosts
        - build_hosts
        - console_hosts
        - forget_status_hosts
        - power_hosts
        search: hostgroup_title ~ lab
      - permissions:
        - view_params
        search: ""
      - permissions:
        - view_media
        search: name ~ "Debian" or name ~ "Windows" or name ~ "ESXi"
      - permissions:
        - view_operatingsystems
        search: name ~ "Debian" or name ~ "Windows" or name ~ "ESXi"
      - permissions:
        - view_ptables
        search: name = "Preseed default LVM" or name = "Windows default partition table" or name = "Kickstart default"
      - permissions:
        - view_provisioning_templates
        search: ""
      - permissions:
        - view_subnets
        search: ""

###################################################################################################
#  _  _  ___  ___ _____ ___ ___  ___  _   _ ___  ___
# | || |/ _ \/ __|_   _/ __| _ \/ _ \| | | | _ \/ __|
# | __ | (_) \__ \ | || (_ |   / (_) | |_| |  _/\__ \
# |_||_|\___/|___/ |_| \___|_|_\\___/ \___/|_|  |___/
#
###################################################################################################

  - name: Hostgroups users
    description: Give user perms to view Hostgroup
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
          - view_hostgroups
        search: ""

  - name: Hostgroups admins
    description: Give admin perms to manage Hostgroup
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
          - view_hostgroups
          - create_hostgroups
          - destroy_hostgroups
          - edit_hostgroups
        search: ""

###################################################################################################
#   ___ ___  __  __ ___ _   _ _____ ___    ___ ___ ___  ___  _   _ ___  ___ ___ ___
#  / __/ _ \|  \/  | _ \ | | |_   _| __|  | _ \ __/ __|/ _ \| | | | _ \/ __| __/ __|
# | (_| (_) | |\/| |  _/ |_| | | | | _|   |   / _|\__ \ (_) | |_| |   / (__| _|\__ \
#  \___\___/|_|  |_|_|  \___/  |_| |___|  |_|_\___|___/\___/ \___/|_|_\\___|___|___/
#
###################################################################################################

  - name: Compute resources admins
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - view_compute_resources
        - create_compute_resources
        - edit_compute_resources
        - destroy_compute_resources
        - power_vm_compute_resources
        - destroy_vm_compute_resources
        search: ""

  - name: Compute resources users vc-dc1
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - console_compute_resources_vms
        - create_compute_resources_vms
        - destroy_compute_resources_vms
        - edit_compute_resources_vms
        - power_compute_resources_vms
        - view_compute_resources
        - view_compute_resources_vms
        search: name = vc-dc1

  - name: Compute resources users vc-dc2
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - console_compute_resources_vms
        - create_compute_resources_vms
        - destroy_compute_resources_vms
        - edit_compute_resources_vms
        - power_compute_resources_vms
        - view_compute_resources
        - view_compute_resources_vms
        search: name = vc-dc2

###################################################################################################
#   ___ ___  __  __ ___ _   _ _____ ___    ___ ___  ___  ___ ___ _
#  / __/ _ \|  \/  | _ \ | | |_   _| __|  | _ \ _ \/ _ \| __|_ _| |
# | (_| (_) | |\/| |  _/ |_| | | | | _|   |  _/   / (_) | _| | || |__
#  \___\___/|_|  |_|_|  \___/  |_| |___|  |_| |_|_\\___/|_| |___|____|
#
###################################################################################################

  - name: Compute profiles users
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - view_compute_profiles
        search: not 1-Small and not 2-Medium and not 3-Large

  - name: Compute profiles Debian
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - view_compute_profiles
        search: name ~ debian

  - name: Compute profiles Windows
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - view_compute_profiles
        search: name ~ windows

###################################################################################################
#  ___ __  __   _   ___ _____    ___ ___  _____  ____   __
# / __|  \/  | /_\ | _ \_   _|  | _ \ _ \/ _ \ \/ /\ \ / /
# \__ \ |\/| |/ _ \|   / | |    |  _/   / (_) >  <  \ V /
# |___/_|  |_/_/ \_\_|_\ |_|    |_| |_|_\\___/_/\_\  |_|
#
###################################################################################################

  - name: Smart proxies users
    description: 
    state: present
    filters: 
      - permissions: 
        - view_smart_proxies
        search: ""

###################################################################################################
#  _    ___   ___   _ _____ ___ ___  _  _ ___
# | |  / _ \ / __| /_\_   _|_ _/ _ \| \| / __|
# | |_| (_) | (__ / _ \| |  | | (_) | .` \__ \
# |____\___/ \___/_/ \_\_| |___\___/|_|\_|___/
#
###################################################################################################

  - name: Locations users
    description: 
    state: present
    filters: 
      - permissions: 
        - view_locations
        search: ""

###################################################################################################
#  _   _ ___ ___ ___  ___ ___  ___  _   _ ___  ___
# | | | / __| __| _ \/ __| _ \/ _ \| | | | _ \/ __|
# | |_| \__ \ _||   / (_ |   / (_) | |_| |  _/\__ \
#  \___/|___/___|_|_\\___|_|_\\___/ \___/|_|  |___/
#
###################################################################################################

  - name: Usergroups users
    description: 
    state: present
    filters: 
      - permissions: 
        - view_usergroups
        search: ""

###################################################################################################
#  __  __ ___ ___  ___
# |  \/  |_ _/ __|/ __|
# | |\/| || |\__ \ (__
# |_|  |_|___|___/\___|
#
###################################################################################################

  - name: Access dashboard
    description: Give access to dashboard
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
          - access_dashboard
        search: ""

  - name: Ansible users
    description: Ansible users role
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
          - view_ansible_roles
        search: ""
      - permissions:
          - view_ansible_variables
          - edit_ansible_variables
        search: ""

  - name: Ansible admins
    description: Ansible admins role
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions:
          - view_ansible_roles
          - import_ansible_roles
        search: ""
      - permissions:
          - view_ansible_variables
          - edit_ansible_variables
          - create_ansible_variables
          - import_ansible_variables
        search: ""

  - name: Env production
    description: 
    locations: LAB
    organizations: LAB
    state: present
    filters: 
      - permissions: 
        - view_environments
        search: name = production


  # - name: 
  #   description: 
  #   state: present
  #   locations: ""
  #   organizations: ""
  #   filters: 
  #     - permissions: ""
  #       search: ""
