---
collections:
  - community.general
  - community.postgresql
  # - community.mysql
  # - community.crypto
  - theforeman.operations
  - theforeman.foreman
  # - theforeman.foreman_scap_client

  # - community.vmware
  - openstack.cloud
  # - lae.proxmox

  # - devsec.hardening

  # - netbox.netbox
  # - community.hashi_vault

  # - cisco.ise:2.2.2
  # - cisco.aci:2.1.0
  # - cisco.ios:2.6.0
  # - cisco.nxos:2.9.0
  # - cisco.asa:2.1.0
  # - f5networks.f5_modules
  # - f5networks.f5_bigip
  # - paloaltonetworks.panos
  # - juniper.device
