---

collections:
  - community.general
  - community.postgresql
  - community.mysql
  - community.crypto
  - devsec.hardening
  - theforeman.foreman
  - theforeman.operations
  # - theforeman.foreman_scap_client
  - openstack.cloud
  # - community.vmware
  # - lae.proxmox
  - icinga.icinga
  # - community.hashi_vault
  # - netbox.netbox
  # - cisco.ise
  # - cisco.aci
  # - cisco.ios
  # - cisco.nxos
  # - cisco.asa
  # - f5networks.f5_modules
  # - f5networks.f5_bigip
  # - paloaltonetworks.panos
  # - juniper.device

roles:
  - geerlingguy.mysql
  - geerlingguy.apache