---

collections:
  - name: community.general
  - name: community.postgresql
  - name: community.mysql
  - name: community.crypto
  - name: devsec.hardening
  - name: theforeman.foreman
  - name: theforeman.operations
  # - name: theforeman.foreman_scap_client
  - name: openstack.cloud
  # - name: community.vmware
  # - name: lae.proxmox
  - name: icinga.icinga
  - name: middleware_automation.keycloak
  # - name: community.hashi_vault
  # - name: netbox.netbox
  # - name: cisco.ise
  # - name: cisco.aci
  # - name: cisco.ios
  # - name: cisco.nxos
  # - name: cisco.asa
  # - name: f5networks.f5_modules
  # - name: f5networks.f5_bigip
  # - name: paloaltonetworks.panos
  # - name: juniper.device

roles:
  - name: geerlingguy.mysql
  - name: geerlingguy.apache
  - name: ansible-role-bind
    src: https://github.com/bertvv/ansible-role-bind.git
  - name: ansible-role-grub
    src: https://github.com/robertdebock/ansible-role-grub.git
  - name: ansible-role-openldap
    src: https://github.com/criecm/ansible-role-openldap.git
  - name: ansible-openldap
    src: https://github.com/ajanis/ansible-openldap.git
  - name: ansible-role-deploy-git-repos
    src: https://github.com/gcoop-libre/ansible-role-deploy-git-repos.git
