download_url: https://galaxy.ansible.com/download/netbox-netbox-3.13.0.tar.gz
format_version: 1.0.0
name: netbox
namespace: netbox
server: https://galaxy.ansible.com/api/
signatures: []
version: 3.13.0
version_url: https://galaxy.ansible.com/api/v2/collections/netbox/netbox/versions/3.13.0/
