---
- name: Update-initramfs # noqa no-changed-when
  ansible.builtin.command: update-initramfs -u

- name: Restart auditd # noqa command-instead-of-module no-changed-when
  ansible.builtin.command:
    cmd: service auditd restart # rhel: see: https://access.redhat.com/solutions/2664811
  when: molecule_yml.driver.name | default() != "docker" # restarting auditd in a container does not work

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Remount filesystems
  ansible.posix.mount:
    path: "{{ item }}"
    state: remounted
  loop: "{{ mountpoints_changed }}"
