---

# defaults file for common
foreman_version: '3.9'
puppet_version: puppet7
postgresql_version: 13

foreman_db_username: "{{ vault_foreman_db_username }}"
foreman_db_password: "{{ vault_foreman_db_password }}"
