---

openldap_schemas:
  - core
  - cosine
  - nis
  - inetorgperson
  - rfc2739
openldap_bases:
  rootdn: cn=admin
  suffix: dc=opn,dc=lab
  overlays:
    - dynlist
    - ppolicy
    - smbk5pwd
  indexes:
    - [ "uid,uidNumber,gidNumber,memberUID", "pres,eq" ]
  # slave:
  #   rid: 675
  #   provider: ldaps://ldap1.opn.lab:636
  #   binddn: cn=bind,dc=dn
  #   credentials: bindpw
  #   bindmethod: simple
