---

# defaults file for common
foreman_version: '3.13'
puppet_version: puppet7

# install options
foreman_cmd_options: []
foreman_plugins: []
foreman_compute: []

foreman_proxy_plugins:
  - dynflow
  - salt

plugin_salt: true
plugin_bind: false
plugin_monitoring: false

# configure options
foreman_options: {}
foreman_plugin_options: {}
foreman_compute_options: {}
puppet_options: {}
puppet_server_options: {}

foreman_proxy_plugin_options:
  dynflow-enabled: 'true'
  dynflow-console-auth: 'true'
  dynflow-database-path: '/var/lib/foreman-proxy/dynflow.sqlite3'
  dynflow-listen-on: 'https'
  salt-listen-on: 'https'
  salt-user: 'root'
  salt-api: 'true'
  salt-api-auth: 'pam'
  salt-api-url: 'https://localhost:9191'
  salt-api-username: 'saltuser'
  salt-api-password: 'saltpassword'
  salt-autosign-file: '/etc/salt/autosign.conf'
  salt-autosign-key-file: '/var/lib/foreman-proxy/salt/grains/autosign_key'

foreman_proxy_options:
  foreman-base-url: "{{ foreman_url_app }}"
  oauth-consumer-key: "{{oauth_consumer_key|default(omit)}}"
  oauth-consumer-secret: "{{oauth_consumer_secret|default(omit)}}"
  manage-puppet-group: 'true'
  register-in-foreman: 'true'
  registered-name: "{{ inventory_hostname }}"
  trusted-hosts: "{{ groups['tfm_app'][0] }}"
  puppetca: 'false'
  puppet: 'false'
  http: 'true'

_salt_test: true
