---

foreman_location:

  - name: LAB5
    organizations: 
      - LAB5
    parent: 

  - name: INFRA
    organizations: 
      - LAB5
    parent: LAB5

  # - name: DNS
  #   organizations: 
  #     - LAB01
  #   parent: LAB01/INFRA

  - name: FOREMAN
    organizations: 
      - LAB5
    parent: LAB5/INFRA

  # - name: PROXMOX
  #   organizations: 
  #     - LAB5
  #   parent: LAB01/INFRA
