---
foreman_version: '3.10'

# accès a l'app foreman lab déployée pour provisioning
foreman_host_app: "{{ groups['tfm_app'][0] }}"
foreman_host_proxy: "{{ groups['tfm_proxy'][0] }}"
foreman_host_puppet: "{{ groups['tfm_puppet'][0] }}"
foreman_host_puppetserver: "{{ groups['tfm_db'][0] }}"

foreman_url_app: "https://{{ foreman_host_app }}"
foreman_url_app_http: "http://{{ foreman_host_app }}"
foreman_url_proxy: "https://{{ foreman_host_proxy }}:8443"
foreman_url_puppet: "https://{{ foreman_host_puppet }}:8140"

# db var
foreman_db_manage: 'false'
foreman_db_name: foreman
foreman_db_username: "{{ vault_foreman_db_username }}"
foreman_db_password: "{{ vault_foreman_db_password }}"

# initial default
foreman_admin_username: "{{ vault_foreman_admin_username }}"
foreman_admin_password: "{{ vault_foreman_admin_password }}"
initial_organization: LAB5
initial_location: LAB5
