---

foreman_compute_resources:

  - name: opn-admin
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: admin
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab1
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab1
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab2
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab2
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab3
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab3
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab4
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab4
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab5
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab5
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab6
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab6
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab7
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab7
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default

  - name: opn-lab8
    organizations:
      - OPN
    locations:
      - OPN
    provider: Openstack
    provider_params:
      url: https://192.168.133.3:5000/v3
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: lab8
      domain: opn.lab
      project_domain_name: Default
      project_domain_id: default
