---

foreman_hostgroup:

###########################################################################################
# opn
###########################################################################################

  - name: opn
    parent: 
    organizations:
      - OPN
    locations:
      - OPN
    parameters:
      # - name: "http-proxy"
      #   parameter_type: string
      #   value: "192.168.133.251"
      # - name: "http-proxy-port"
      #   parameter_type: string
      #   value: "3128"
      - name: "lang"
        parameter_type: string
        value: "fr_FR.UTF8"
      - name: "time-zone"
        parameter_type: string
        value: "Europe/Paris"

###########################################################################################
# opn/foreman
###########################################################################################

  - name: foreman
    parent: opn
    organizations:
      - OPN
    locations:
      - OPN

  - name: app
    parent: opn/foreman
    organizations:
      - OPN
    locations:
      - OPN

  - name: db
    parent: opn/foreman
    organizations:
      - OPN
    locations:
      - OPN

  - name: puppet
    parent: opn/foreman
    organizations:
      - OPN
    locations:
      - OPN

  - name: proxy
    parent: opn/foreman
    organizations:
      - OPN
    locations:
      - OPN
    puppetclasses:
      - foreman_proxy

  # - name: dns
  #   parent: opn/foreman
  #   organizations: 
  #     - OPN
  #   locations:
  #     - OPN

###########################################################################################
# lab/os
###########################################################################################

  - name: os
    parent: opn
    organizations:
      - OPN
    locations:
      - OPN

  - name: centos
    parent: opn/os
    organizations:
      - OPN
    locations:
      - OPN
    parameters:
      - name: "bootloader-append"
        parameter_type: string
        value: "nofb quiet splash=quiet"
      - name: "disable-firewall"
        parameter_type: boolean
        value: "true"
      - name: "enable-epel"
        parameter_type: boolean
        value: "true"
      - name: "enable-puppetlabs-puppet6-repo"
        parameter_type: boolean
        value: "true"
      - name: "keyboard"
        parameter_type: string
        value: "fr"
      - name: "lang"
        parameter_type: string
        value: "fr_FR.UTF-8"
      - name: "time-zone"
        parameter_type: string
        value: "Europe/Paris"
      - name: "package_upgrade"
        parameter_type: boolean
        value: "true"
      - name: "selinux-mode"
        parameter_type: string
        value: "enforcing"

  - name: debian
    parent: opn/os
    organizations:
      - OPN
    locations:
      - OPN
    parameters:
      - name: "additional-packages"
        parameter_type: string
        value: "gnupg ccze qemu-guest-agent"
      - name: "enable-puppetlabs-puppet7-repo"
        parameter_type: boolean
        value: "true"

  # - name: windows
  #   parent: opn/os
  #   organizations: 
  #     - OPN
  #   locations:
  #     - OPN
  #   parameters:
  #     - name: ansible_become
  #       parameter_type: string
  #       value: false
  #     - name: ansible_become_method
  #       parameter_type: string
  #       value: runas
  #     - name: ansible_become_pass
  #       parameter_type: string
  #       value: papillon
  #     - name: ansible_become_user
  #       parameter_type: string
  #       value: Administrateur
  #     - name: ansible_connection
  #       parameter_type: string
  #       value: winrm
  #     - name: ansible_gather_facts
  #       parameter_type: boolean
  #       value: false
  #     - name: ansible_os_family
  #       parameter_type: string
  #       value: Windows
  #     - name: ansible_user
  #       parameter_type: string
  #       value: Administrateur
  #     - name: ansible_winrm_scheme
  #       parameter_type: string
  #       value: http
  #     - name: ansible_winrm_server_cert_validation
  #       parameter_type: string
  #       value: ignore
  #     - name: ansible_winrm_transport
  #       parameter_type: string
  #       value: basic
  #     - name: foremanDebug
  #       parameter_type: string
  #       value: false
  #     - name: remote_execution_ssh_password
  #       parameter_type: string
  #       value: papillon

  # - name: esxi
  #   parent: opn/os
  #   organizations: 
  #     - OPN
  #   locations:
  #     - OPN
  #   parameters:
  #     - name: serialnum
  #       parameter_type: string
  #       value: JV425-4H100-VZHH8-Q23NP-3A9PP
  #   environment: lab
  #   compute_resource: pve-gsw
  #   compute_profile: esxi-medium
  #   architecture: x86_64
  #   operatingsystem: ESXi-7.0.3-19193900
  #   medium: ESXi dummy
  #   ptable: Kickstart default
  #   pxe_loader: iPXE Chain BIOS

  # - name: vcenter
  #   parent: opn/os
  #   organizations: 
  #     - OPN
  #   locations:
  #     - OPN

###########################################################################################
# lab/salt
###########################################################################################

  - name: salt
    parent: opn
    organizations:
      - OPN
    locations:
      - OPN

  - name: master
    parent: opn/salt
    organizations:
      - OPN
    locations:
      - OPN

  - name: syndic
    parent: opn/salt
    organizations:
      - OPN
    locations:
      - OPN

###########################################################################################
# lab/gitea
###########################################################################################

  - name: gitea
    parent: opn
    organizations:
      - OPN
    locations:
      - OPN

###########################################################################################
# lab/gitlab
###########################################################################################

  # - name: gitlab
  #   parent: opn
  #   organizations: 
  #     - OPN
  #   locations:
  #     - OPN

###########################################################################################
# lab/vsphere
###########################################################################################

  - name: vsphere
    parent: opn
    organizations: 
      - OPN
    locations:
      - OPN

  - name: vcenter
    parent: opn/vsphere
    organizations: 
      - OPN
    locations:
      - OPN

  - name: esxi
    parent: opn/vsphere
    organizations: 
      - OPN
    locations:
      - OPN
    parameters:
      # - name: serialnum
      #   parameter_type: string
      #   value: JV425-4H100-VZHH8-Q23NP-3A9PP
  #   # compute_resource: pve-gsw
  #   # compute_profile: esxi-medium
  #   # environment: lab
  #   architecture: x86_64
  #   operatingsystem: ESXi-6.7.0-15160138
  #   medium: ESXi dummy
  #   ptable: Kickstart default
  #   pxe_loader: iPXE Chain BIOS
