---

foreman_location:

  - name: OPN
    organizations: 
      - OPN
    parent: 

  - name: INFRA
    organizations: 
      - OPN
    parent: OPN

  # - name: DNS
  #   organizations: 
  #     - OPN
  #   parent: OPN/INFRA

  - name: FOREMAN
    organizations: 
      - OPN
    parent: OPN/INFRA

  # - name: PROXMOX
  #   organizations: 
  #     - OPN
  #   parent: OPN/INFRA
