---

foreman_subnets:

  - name: VLAN5
    description: VLAN5
    network: 192.168.135.0
    mask: 255.255.255.0
    gateway: 192.168.135.1
    dns_primary: 192.168.133.249
    dns_secondary: 192.168.133.251
    ipam: Internal DB
    from_ip: 192.168.135.14
    to_ip: 192.168.135.244
    boot_mode: Static
    # dhcp_proxy: "{{ foreman_host_proxy }}"
    # tftp_proxy: "{{ foreman_host_proxy }}"
    # httpboot_proxy: "{{ foreman_host_proxy }}"
    # template_proxy: "{{ foreman_host_proxy }}"
    # discovery_proxy: "{{ foreman_host_proxy }}"
    remote_execution_proxies: "{{ foreman_host_proxy }}"
    mtu: 1500
    domains:
      - opn.lab
    locations:
      - OPN
    organizations:
      - OPN

  - name: VLAN5_ADM
    description: VLAN5_ADM
    network: 192.168.5.0
    mask: 255.255.255.0
    gateway: 192.168.5.1
    dns_primary: 192.168.133.249
    dns_secondary: 192.168.133.251
    ipam: Internal DB
    from_ip: 192.168.5.14
    to_ip: 192.168.5.244
    boot_mode: Static
    # dhcp_proxy: "{{ foreman_host_proxy }}"
    # tftp_proxy: "{{ foreman_host_proxy }}"
    # httpboot_proxy: "{{ foreman_host_proxy }}"
    # template_proxy: "{{ foreman_host_proxy }}"
    # discovery_proxy: "{{ foreman_host_proxy }}"
    remote_execution_proxies: "{{ foreman_host_proxy }}"
    mtu: 1500
    domains:
      - opn.lab
    locations:
      - OPN
    organizations:
      - OPN
