---

foreman_usergroup:

  - name: admins
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-admin
      - Hostgroups admins
      - Hosts admins
      - Ansible admins

  - name: sysadm
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-admin
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB1
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab1
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB2
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab2
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB3
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab3
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB4
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab4
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB5
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab5
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB6
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab6
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB7
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab7
      - Hostgroups users
      - Hosts admins
      - Ansible admins

  - name: LAB8
    admin: false
    roles:
      - Access dashboard
      - Env production
      - Locations users
      - Organization users
      - Usergroups users
      - Smart proxies users
      - Compute images users
      - Compute profiles users
      - Compute resources users opn-lab8
      - Hostgroups users
      - Hosts admins
      - Ansible admins

foreman_external_usergroup:

  - name: tfm-admin
    auth_source: opn-ldap1
    usergroup: admins

  - name: tfm-admsys
    auth_source: opn-ldap1
    usergroup: sysadm

  - name: tfm-lab1
    auth_source: opn-ldap1
    usergroup: LAB1
  - name: tfm-lab2
    auth_source: opn-ldap1
    usergroup: LAB2
  - name: tfm-lab3
    auth_source: opn-ldap1
    usergroup: LAB3
  - name: tfm-lab4
    auth_source: opn-ldap1
    usergroup: LAB4
  - name: tfm-lab5
    auth_source: opn-ldap1
    usergroup: LAB5
  - name: tfm-lab6
    auth_source: opn-ldap1
    usergroup: LAB6
  - name: tfm-lab7
    auth_source: opn-ldap1
    usergroup: LAB7
  - name: tfm-lab8
    auth_source: opn-ldap1
    usergroup: LAB8
