---

foreman_compute_resources:

  # - name: vc-dc1
  #   organizations:
  #     - LAB
  #   locations:
  #     - LAB
  #   provider: vmware
  #   provider_params:
  #     url: vc-dc1.lab.loxda.net
  #     user: administrator@lab.loxda.net
  #     password: P4p1llon!!
  #     datacenter: DC-DC1

  # - name: vc-dc2
  #   organizations:
  #     - LAB
  #   locations:
  #     - LAB
  #   provider: vmware
  #   provider_params:
  #     url: vc-dc2.lab.loxda.net
  #     user: administrator@lab.loxda.net
  #     password: P4p1llon!!
  #     datacenter: DC-DC2

  - name: opn
    organizations:
      - LAB01
    locations:
      - LAB01
    provider: Openstack
    provider_params:
      url: "https://192.168.83.135:5000/v3"
      user: admin
      password: b0004c7b0217ec419ec562a66bee2b7daf733a2e286c2c
      tenant: "lab01"
      domain: "lab01.opn.lab"
      project_domain_name: "Default"
      project_domain_id: "default"
