---

foreman_location:

  - name: LAB01
    organizations: 
      - LAB01
    parent: 

  - name: INFRA
    organizations: 
      - LAB01
    parent: LAB01

  # - name: DNS
  #   organizations: 
  #     - LAB01
  #   parent: LAB01/INFRA

  - name: FOREMAN
    organizations: 
      - LAB01
    parent: LAB01/INFRA

  # - name: PROXMOX
  #   organizations: 
  #     - LAB01
  #   parent: LAB01/INFRA

  # - name: v10
  #   organizations: 
  #     - OPN
  #   parent: LAB
  # - name: v11
  #   organizations: 
  #     - OPN
  #   parent: LAB
  # - name: v12
  #   organizations: 
  #     - OPN
  #   parent: LAB
  # - name: v13
  #   organizations: 
  #     - OPN
  #   parent: LAB
