---

- hosts: tfm_app
  gather_facts: false

  module_defaults:

    group/theforeman.foreman.foreman:
      username: "{{ foreman_admin_username }}"
      password: "{{ foreman_admin_password }}"
      server_url: "{{ foreman_url_app }}"
      validate_certs: false

    theforeman.foreman.host:
      enabled: true
      organization: OPN
      location: OPN
      owner_group: "{{ owner_group }}"
      hostgroup: "{{ host_group }}"
      provision_method: build
      operatingsystem: "{{ operating_system }}"
      medium: "{{ medium }}"
      architecture: x86_64
      pxe_loader: PXELinux BIOS
      environment: "{{ env }}"
      ptable: "{{ ptable }}"
      root_pass: "{{ root_pass }}"
      compute_resource: "{{ computer_resource }}"
      compute_profile: "{{ compute_profile }}"
      compute_attributes:
        cpus: "{{ vm_cpu_count }}"
        memory_mb: "{{ vm_memory }}"
        interfaces_attributes:
          - type: "interface"
            primary: true
            compute_attributes:
            name: nic1
            network: "{{ vm_vlan_name1 }}"
            interface: "{{ vm_interface1 }}"
            subnet: "{{ vm_subnet1 }}"
            ip: "{{ vm_ip1 }}"
            domain: "{{ domain1 }}"
            provision: yes
          - type: "interface"
            primary: true
            compute_attributes:
            name: nic2
            network: "{{ vm_vlan_name2 }}"
            interface: "{{ vm_interface2 }}"
            subnet: "{{ vm_subnet2 }}"
            ip: "{{ vm_ip2 }}"
            domain: "{{ domain2 }}"
            provision: yes
        volumes_attributes:
          0:
            size_gb: 20
            datastore: "{{ datastore }}"
            thin: false
            eager_zero: false
  tasks:

    - name: "Create a host in foreman on openstack"
      delegate_to: localhost
      theforeman.foreman.host:
        name: "{{ inventory_hostname }}"
        state: present
