---

- hosts: localhost
  serial: 1
  gather_facts: false

  vars:
    foreman_url_app: https://tfm-app.opn.lab
    username: bob1
    password: papillon
    compute_resource: opn-test1
    compute_profile: debian-small
    image: Debian12
    hostgroup: opn/os/debian
    owner_group: TEST1
    root_pass: papillon

  module_defaults:

    group/theforeman.foreman.foreman:
      username: "{{ username | d('bob1') }}"
      password: "{{ password | d('papillon') }}"
      server_url: "{{ foreman_url_app }}"
      validate_certs: false

    theforeman.foreman.host:
      enabled: true
      image: "{{ image }}"
      hostgroup: "{{ hostgroup | d('production') }}"
      root_pass: "{{ root_pass | d('password') }}"
      environment: "{{ env | d('production') }}"
      organization: "{{ organization | d('OPN') }}"
      location: "{{ location | d('OPN') }}"
      owner_group: "{{ owner_group | d('sysadm') }}"
      operatingsystem: "{{ operatingsystem | d('Debian 12') }}"
      medium: "{{ medium | d('Debian mirror') }}"
      architecture: "{{ architecture | d('x86_64') }}"
      pxe_loader: "{{ pxe_loader | d('None') }}"
      ptable: "{{ ptable | d('Preseed default LVM') }}"
      provision_method: "{{ provision_method | d('image') }}"
      compute_resource: "{{ compute_resource | d('opn-test1') }}"
      compute_profile: "{{ compute_profile | d('debian-small') }}"
      compute_attributes:
        availability_zone: nova
        security_groups:
          - ALLOW_ALL
        boot_from_volume: false
        size_gb: 8
        nics:
          - 3225e32e-fb3b-4d4b-bf08-40f69e4e6e75

  tasks:

    - block:

      - name: "Create a host in foreman on openstack"
        delegate_to: localhost
        theforeman.foreman.host:
          name: "{{ lookup('community.general.random_pet') }}.opn.lab"
          state: present
        register: host

      - name: Display host created
        ansible.builtin.debug:
          msg: |
            Name: {{host.entity.hosts[0].name}}
            FQDN: fqdn
            IPaddr: ipaddr

            debug: {{host.entity.hosts[0]}}

      # loop: "{{ range(0,2) | list }}"
      # loop_control:
      #   pause: 60
      ignore_errors: true

    # - name: Test2 api
    #   ansible.builtin.uri:
    #     user: "admin"
    #     password: "P4p1llon!!"
    #     force_basic_auth: true
    #     validate_certs: false
    #     url: "{{ foreman_url_app }}/api/compute_resources?search=name%3Dopn-test1"
    #     method: GET
    #     status_code:
    #       - 200
    #   until: uri_output.status == 200
    #   retries: 24
    #   delay: 5
    #   register: uri_output

    # - name: Display Target Variables
    #   ansible.builtin.debug:
    #     msg: '{{uri_output.json.results}}'
  
    # - name: Test api
    #   ansible.builtin.uri:
    #     user: "admin"
    #     password: "P4p1llon!!"
    #     validate_certs: false
    #     url: "{{ foreman_url_app }}/api/compute_resources/1/compute_attributes"
    #     method: GET
    #     force_basic_auth: true
    #   register: toto

    # - name: Display Target Variables
    #   ansible.builtin.debug:
    #     msg: '{{toto}}'        
