---

- hosts: all
  gather_facts: true
  become: true

  tasks:

  - name: Update CA Certificates
    ansible.builtin.apt:
      name: ca-certificates
      update_cache: yes

  - name: Creating certs file in /usr/local/share/ca-certificates
    ansible.builtin.copy:
      dest: "{{ item.name }}"
      content: "{{ item.filecontent }}"
      owner: root
      group: root
      mode: 0644
    loop: "{{ vault_ca_certs_files }}"

  - name: Update ca-certificates
    ansible.builtin.shell: |
      update-ca-certificates
