---
- name: Déploiement de la configuration des certificats
  hosts: all
  gather_facts: true
  become: true

  tasks:
    - name: S'assurer que le paquet ca-certificates est installé
      ansible.builtin.apt:
        name: ca-certificates
        state: present
        update_cache: yes

    - name: Déployer les certificats CA personnalisés
      ansible.builtin.copy:
        dest: "/usr/local/share/ca-certificates/{{ item.name | basename }}"
        content: "{{ item.filecontent }}"
        owner: root
        group: root
        mode: 0644
      loop: "{{ vault_ca_certs_files | default([]) }}"
      notify: mettre à jour les certificats ca
      when: vault_ca_certs_files is defined

  handlers:
    - name: mettre à jour les certificats ca
      ansible.builtin.command: update-ca-certificates
      changed_when: false
      args:
        warn: false
