---

- import_playbook: foreman_puppet.yml
- import_playbook: foreman_db.yml
- import_playbook: foreman_app.yml
- import_playbook: foreman_proxy.yml
- import_playbook: foreman_provisioning.yml
    
# maintain
# apt: ruby-foreman-maintain
# foreman-maintain maintenance-mode start
# foreman-maintain maintenance-mode stop
# mkdir -p /mnt/{backup,snap}/ ; mount -t nfs4 172.16.202.10:/nfs/foreman/lab /mnt/backup/
# foreman-maintain advanced procedure by-tag backup --backup-dir /mnt/backup/app/ --mount-dir /mnt/snap/ --online-backup --assumeyes --plaintext --preserve-dir --skip-pulp --whitelist="foreman-db-up,backup-metadata,backup-snapshot-logical-volume-confirmation"
# foreman-maintain restore --dry-run /mnt/backup/app/
