---

# deploy puppetserver
- hosts: tfm_puppet
  gather_facts: true
  roles:
    - role: ansible-role-grub
    - role: foreman-puppet
  tags:
    - tfm
    - puppet

- hosts: tfm_db
  gather_facts: true
  roles:
    - role: ansible-role-grub
    - role: foreman-db
  tags:
    - tfm
    - db

# deploy theforeman app
- hosts: tfm_app
  gather_facts: true
  roles:
    - role: ansible-role-grub
    - role: foreman-app
  tags:
    - tfm
    - app

# fetch oauth_consumer_* info
- hosts: "{{ groups['tfm_app'][0] }}"
  gather_facts: true
  tasks:
    - name: Fetch settings.yaml
      slurp:
        src: /etc/foreman/settings.yaml
      register: settingsyaml
    - name: Fetch oauth_consumer_key
      set_fact:
        oauth_consumer_key: "{{ settingsyaml['content'] | b64decode | regex_findall(':oauth_consumer_key: (.+)') | first }}"
    - name: Fetch oauth_consumer_secret
      set_fact:
        oauth_consumer_secret: "{{ settingsyaml['content'] | b64decode | regex_findall(':oauth_consumer_secret: (.+)') | first }}"
  tags:
    - tfm
    - app
    - oauth

# deploy theforeman smart_proxy
- hosts: tfm_proxy
  gather_facts: true
  vars:
    oauth_consumer_key: "{{ hostvars[groups['tfm_app'][0]]['oauth_consumer_key'] }}"
    oauth_consumer_secret: "{{ hostvars[groups['tfm_app'][0]]['oauth_consumer_secret'] }}"
  roles:
    - role: ansible-role-grub
    - role: foreman-proxy
  tags:
    - tfm
    - proxy

- hosts: tfm_proxy
  gather_facts: true
  roles:
    - role: ansible-role-deploy-git-repos
  tags:
    - tfm
    - proxy
    - ansible-roles

# There is an omapi bug after isc-dhcp-server_4.4.1-2+deb10u1 (Debian 10 Buster) run with --tags tfm,fixdhcp
- hosts: tfm_proxy
  gather_facts: true
  tasks:
    - name: fix isc-dhcp-server omapi bug with debian >10
      block:
      - name: Download libisc-export1100 package from Buster
        ansible.builtin.apt:
          deb: http://mirror.lab.loxda.net/debian-security/pool/updates/main/b/bind9/libisc-export1100_9.11.5.P4+dfsg-5.1+deb10u9_amd64.deb
      - name: Download libdns-export1104 package from Buster
        ansible.builtin.apt:
          deb: http://mirror.lab.loxda.net/debian-security/pool/updates/main/b/bind9/libdns-export1104_9.11.5.P4+dfsg-5.1+deb10u9_amd64.deb
      - name: Download isc-dhcp-server package from Buster
        get_url:
          url: http://mirror.lab.loxda.net/debian/pool/main/i/isc-dhcp/isc-dhcp-server_4.4.1-2+deb10u1_amd64.deb
          dest: /tmp/isc-dhcp-server_4.4.1-2+deb10u1_amd64.deb
      - name: Fix isc-dhcp-server version
        command: dpkg --force-downgrade --force-hold -i /tmp/isc-dhcp-server_4.4.1-2+deb10u1_amd64.deb
      - name: Hold isc-dhcp-server
        dpkg_selections: name=isc-dhcp-server selection=hold
      - name: Restart service isc-dhcp-server
        service: name=isc-dhcp-server state=restarted
      when: ansible_distribution == 'Debian' and "ansible_distribution_version" >= "10"
  tags:
    - never
    - fixdhcp

# provisioning theforeman instance
- hosts: tfm
  gather_facts: false
  roles:
    - role: foreman-custom
  tags:
    - never
    - provisioning

# maintain
# apt: ruby-foreman-maintain
# foreman-maintain maintenance-mode start
# foreman-maintain maintenance-mode stop
# mkdir -p /mnt/{backup,snap}/ ; mount -t nfs4 172.16.202.10:/nfs/foreman/lab /mnt/backup/
# foreman-maintain advanced procedure by-tag backup --backup-dir /mnt/backup/app/ --mount-dir /mnt/snap/ --online-backup --assumeyes --plaintext --preserve-dir --skip-pulp --whitelist="foreman-db-up,backup-metadata,backup-snapshot-logical-volume-confirmation"
# foreman-maintain restore --dry-run /mnt/backup/app/
